builds:
  # You can have multiple builds defined as a yaml list
  -
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 6

    env:
      - CGO_ENABLED=1
      - CC=arm-linux-gnueabi-gcc
